apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-log-output-dep
  namespace: practice-dwk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-log-output-app
  template:
    metadata:
      labels:
        app: web-log-output-app
    spec:
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: cluster-share
      containers:
        - name: web-log-output-app
          image: isalxmkh/web-log-output-app:v2.07
          env:
            - name: BASE_PING_PONG_URL
              valueFrom:
                configMapKeyRef:
                  name: web-log-output-config-map
                  key: url_to_ping_pong
            - name: MOUNT
              valueFrom:
                configMapKeyRef:
                  name: web-log-output-config-map
                  key: share_path
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  key: message
                  name: web-log-output-config-map
          volumeMounts:
            - name: shared-folder
              mountPath: /usr/src/app/files/
